on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  buidJoB:
    name: buid
    runs-on: macos-14
    steps:
      - uses: actions/checkout@main
        with:
          submodules: 'true'
      - name: Set up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
          xcode-select -p
          xcodebuild -version
      - name: BuildFFmpeg
        run: swift package BuildFFmpeg  -h
      - name: ffprobe
        run: swift run ffprobeCmd -h 
      - name: pod install
        run: |
          cd Demo
          pod install
      - name: xcodebuild macOS
        run: |
          cd Demo
          xcodebuild -workspace Demo.xcworkspace -scheme macOS
      - name: xcodebuild iOS
        run: |
          cd Demo
          xcodebuild -workspace Demo.xcworkspace -scheme iOS -sdk iphonesimulator
          # xcodebuild -workspace Demo.xcworkspace -scheme visonOS -sdk XRSimulator
          # xcodebuild -workspace Demo.xcworkspace -scheme tvOS -sdk appletvsimulator
          
